# Generated by Django 4.2.6 on 2025-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
