# Generated by Django 5.2.4 on 2025-07-26 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_thumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('message', models.TextField(help_text='Enter your message here', max_length=2000, verbose_name='Your Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date/Time')),
                ('is_responded', models.BooleanField(default=False, help_text='Mark if this submission has been responded to', verbose_name='Responded?')),
                ('response_notes', models.TextField(blank=True, help_text='Any notes about the response', max_length=2000, null=True, verbose_name='Response Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
