# Generated by Django 5.2.4 on 2025-09-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ap_api_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
